apiVersion: v1
kind: Service
metadata:
  name: bsl-text2gloss-agent
  namespace: live
  labels:
    app: bsl-text2gloss-agent
spec:
  type: ClusterIP
  ports:
  - port: 8003
  selector:
    app: bsl-text2gloss-agent
