#!/usr/bin/env python3
"""Generate API endpoint catalog from all services."""
import requests
import json
from pathlib import Path

SERVICES = [
    ('OpenClaw Orchestrator', 'http://localhost:8000'),
    ('SceneSpeak Agent', 'http://localhost:8001'),
    ('Captioning Agent', 'http://localhost:8002'),
    ('BSL Agent', 'http://localhost:8003'),
    ('Sentiment Agent', 'http://localhost:8004'),
    ('Lighting-Sound-Music', 'http://localhost:8005'),
    ('Safety Filter', 'http://localhost:8006'),
    ('Operator Console', 'http://localhost:8007'),
    ('Music Generation', 'http://localhost:8011'),
]

output = ["# API Endpoint Catalog\n"]
output.append("Auto-generated catalog of all Project Chimera API endpoints.\n\n")
output.append("> Generated by `scripts/docs/generate-endpoint-catalog.py`\n\n")
output.append("---\n\n")

for service_name, base_url in SERVICES:
    try:
        response = requests.get(f"{base_url}/openapi.json", timeout=5)
        if response.status_code == 200:
            openapi = response.json()
            paths = openapi.get('paths', {})

            output.append(f"## {service_name}\n\n")
            output.append(f"**Base URL:** `{base_url}`\n\n")
            output.append(f"**API Docs:** [{base_url}/docs]({base_url}/docs)\n\n")

            if paths:
                for path, methods in sorted(paths.items()):
                    for method, details in methods.items():
                        summary = details.get('summary', 'No description')
                        tags = details.get('tags', [])
                        operation_id = details.get('operationId', '')

                        output.append(f"### {method.upper()} {path}\n\n")
                        if summary != 'No description':
                            output.append(f"**Summary:** {summary}\n\n")
                        if tags:
                            output.append(f"**Tags:** {', '.join(tags)}\n\n")
                        if operation_id:
                            output.append(f"**Operation ID:** `{operation_id}`\n\n")
                        output.append("---\n\n")
            else:
                output.append("_No endpoints documented_\n\n")
        else:
            output.append(f"## {service_name}\n\n")
            output.append(f"**Base URL:** `{base_url}`\n\n")
            output.append(f"_Unable to fetch endpoints: HTTP {response.status_code}_\n\n")
    except requests.exceptions.Timeout:
        output.append(f"## {service_name}\n\n")
        output.append(f"**Base URL:** `{base_url}`\n\n")
        output.append("_Unable to fetch endpoints: Request timed out_\n\n")
    except requests.exceptions.ConnectionError:
        output.append(f"## {service_name}\n\n")
        output.append(f"**Base URL:** `{base_url}`\n\n")
        output.append("_Unable to fetch endpoints: Service not running_\n\n")
    except Exception as e:
        output.append(f"## {service_name}\n\n")
        output.append(f"**Base URL:** `{base_url}`\n\n")
        output.append(f"_Unable to fetch endpoints: {e}_\n\n")

# Write to file
output_path = Path('docs/api/endpoints.md')
output_path.write_text(''.join(output))
print(f"API endpoint catalog generated at {output_path}")
