"""
Coverage Collector - OpenClaw Test Orchestrator

Collects and analyzes code coverage data.
"""

import logging
import json
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class FileCoverage:
    """
    Coverage data for a single file.

    Attributes:
        path: File path
        total_lines: Total number of lines
        covered_lines: Number of covered lines
        percentage: Coverage percentage
        missing_lines: List of uncovered line numbers
    """
    path: str
    total_lines: int
    covered_lines: int
    percentage: float
    missing_lines: List[int] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "path": self.path,
            "total_lines": self.total_lines,
            "covered_lines": self.covered_lines,
            "percentage": round(self.percentage, 2),
            "missing_lines": self.missing_lines
        }


@dataclass
class CoverageData:
    """
    Coverage data for a service or project.

    Attributes:
        total_lines: Total lines across all files
        covered_lines: Total covered lines
        percentage: Overall coverage percentage
        files: Coverage per file
    """
    total_lines: int
    covered_lines: int
    percentage: float
    files: Dict[str, FileCoverage] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "total_lines": self.total_lines,
            "covered_lines": self.covered_lines,
            "percentage": round(self.percentage, 2),
            "files": {
                path: fc.to_dict()
                for path, fc in self.files.items()
            }
        }

    def to_json(self) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict(), indent=2)


@dataclass
class CoverageReport:
    """
    Complete coverage report for a service.

    Attributes:
        service: Service name
        coverage: Coverage data
        timestamp: Report timestamp
        run_id: Associated test run ID
    """
    service: str
    coverage: CoverageData
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    run_id: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "service": self.service,
            "coverage": self.coverage.to_dict(),
            "timestamp": self.timestamp,
            "run_id": self.run_id
        }

    def to_json(self) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict(), indent=2)


class CoverageCollector:
    """
    Collects and analyzes code coverage data.

    Parses coverage.json files generated by pytest-cov.
    """

    def __init__(self):
        """Initialize coverage collector."""
        logger.info("CoverageCollector initialized")

    def parse_coverage_json(self, coverage_file: Path) -> Optional[CoverageData]:
        """
        Parse coverage.json file.

        Args:
            coverage_file: Path to coverage.json

        Returns:
            CoverageData or None if file doesn't exist
        """
        if not coverage_file.exists():
            logger.warning(f"Coverage file not found: {coverage_file}")
            return None

        try:
            with open(coverage_file) as f:
                data = json.load(f)

            # Extract totals
            totals = data.get("totals", {})
            total_lines = totals.get("num_statements", 0)
            covered_lines = totals.get("covered_lines", 0)
            percentage = totals.get("percent_covered", 0.0)

            # Extract per-file coverage
            files = {}
            for file_path, file_data in data.get("files", {}).items():
                summary = file_data.get("summary", {})
                missing = file_data.get("missing_lines", [])

                files[file_path] = FileCoverage(
                    path=file_path,
                    total_lines=summary.get("num_statements", 0),
                    covered_lines=summary.get("covered_lines", 0),
                    percentage=summary.get("percent_covered", 0.0),
                    missing_lines=missing
                )

            return CoverageData(
                total_lines=total_lines,
                covered_lines=covered_lines,
                percentage=percentage,
                files=files
            )

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse coverage.json: {e}")
            return None
        except Exception as e:
            logger.error(f"Error reading coverage file: {e}")
            return None

    def generate_report(
        self,
        service: str,
        coverage_file: Path,
        run_id: Optional[str] = None
    ) -> Optional[CoverageReport]:
        """
        Generate coverage report from coverage.json.

        Args:
            service: Service name
            coverage_file: Path to coverage.json
            run_id: Associated test run ID

        Returns:
            CoverageReport or None if parsing fails
        """
        coverage_data = self.parse_coverage_json(coverage_file)

        if coverage_data is None:
            return None

        return CoverageReport(
            service=service,
            coverage=coverage_data,
            run_id=run_id
        )

    def collect_from_service(
        self,
        service_path: str,
        service_name: str,
        run_id: Optional[str] = None
    ) -> Optional[CoverageReport]:
        """
        Collect coverage data from a service directory.

        Args:
            service_path: Path to service directory
            service_name: Service name
            run_id: Associated test run ID

        Returns:
            CoverageReport or None if no coverage file found
        """
        path = Path(service_path)
        coverage_file = path / "coverage.json"

        return self.generate_report(service_name, coverage_file, run_id)

    def aggregate_reports(self, reports: List[CoverageReport]) -> CoverageData:
        """
        Aggregate coverage from multiple reports.

        Args:
            reports: List of coverage reports

        Returns:
            Aggregated CoverageData
        """
        total_lines = 0
        covered_lines = 0
        all_files = {}

        for report in reports:
            coverage = report.coverage
            total_lines += coverage.total_lines
            covered_lines += coverage.covered_lines

            # Merge file coverage
            for file_path, file_cov in coverage.files.items():
                # Use service name as prefix to avoid conflicts
                prefixed_path = f"{report.service}/{file_path}"

                if prefixed_path in all_files:
                    # Sum up coverage for same file
                    existing = all_files[prefixed_path]
                    all_files[prefixed_path] = FileCoverage(
                        path=prefixed_path,
                        total_lines=existing.total_lines + file_cov.total_lines,
                        covered_lines=existing.covered_lines + file_cov.covered_lines,
                        percentage=0.0,  # Recalculated below
                        missing_lines=[]  # Aggregated, don't track
                    )
                else:
                    all_files[prefixed_path] = FileCoverage(
                        path=prefixed_path,
                        total_lines=file_cov.total_lines,
                        covered_lines=file_cov.covered_lines,
                        percentage=file_cov.percentage,
                        missing_lines=file_cov.missing_lines
                    )

        # Calculate percentages
        for file_cov in all_files.values():
            if file_cov.total_lines > 0:
                file_cov.percentage = (
                    file_cov.covered_lines / file_cov.total_lines
                ) * 100

        # Calculate overall percentage
        overall_percentage = (
            covered_lines / total_lines * 100
        ) if total_lines > 0 else 0.0

        return CoverageData(
            total_lines=total_lines,
            covered_lines=covered_lines,
            percentage=overall_percentage,
            files=all_files
        )

    def get_uncovered_files(
        self,
        coverage: CoverageData,
        threshold: float = 100.0
    ) -> List[str]:
        """
        Get list of files below coverage threshold.

        Args:
            coverage: Coverage data
            threshold: Minimum coverage percentage

        Returns:
            List of file paths below threshold
        """
        uncovered = []

        for file_path, file_cov in coverage.files.items():
            if file_cov.percentage < threshold:
                uncovered.append(file_path)

        return sorted(uncovered, key=lambda p: coverage.files[p].percentage)

    def filter_by_coverage(
        self,
        coverage: CoverageData,
        min_percentage: float = 0.0,
        max_percentage: float = 100.0,
        below: bool = False
    ) -> Dict[str, FileCoverage]:
        """
        Filter files by coverage range.

        Args:
            coverage: Coverage data
            min_percentage: Minimum coverage
            max_percentage: Maximum coverage
            below: If True, returns files BELOW min_percentage

        Returns:
            Dictionary of filtered files
        """
        filtered = {}

        for file_path, file_cov in coverage.files.items():
            if below:
                if file_cov.percentage < min_percentage:
                    filtered[file_path] = file_cov
            else:
                if min_percentage <= file_cov.percentage <= max_percentage:
                    filtered[file_path] = file_cov

        return filtered

    def format_summary(self, coverage: CoverageData) -> str:
        """
        Format coverage summary as string.

        Args:
            coverage: Coverage data

        Returns:
            Formatted summary string
        """
        return (
            f"Coverage: {coverage.percentage:.1f}% "
            f"({coverage.covered_lines}/{coverage.total_lines} lines)"
        )

    def format_file_list(self, coverage: CoverageData) -> str:
        """
        Format file coverage list.

        Args:
            coverage: Coverage data

        Returns:
            Formatted file list
        """
        lines = []
        lines.append("File Coverage:")
        lines.append("-" * 60)

        # Sort by coverage percentage
        sorted_files = sorted(
            coverage.files.items(),
            key=lambda x: x[1].percentage
        )

        for file_path, file_cov in sorted_files:
            lines.append(
                f"  {file_cov.percentage:6.1f}%  {file_path} "
                f"({file_cov.covered_lines}/{file_cov.total_lines})"
            )

        lines.append("-" * 60)
        lines.append(f"Total: {coverage.percentage:.1f}%")

        return "\n".join(lines)

    def get_coverage_delta(
        self,
        before: CoverageData,
        after: CoverageData
    ) -> Dict[str, float]:
        """
        Calculate coverage change between two measurements.

        Args:
            before: Previous coverage
            after: New coverage

        Returns:
            Delta information
        """
        return {
            "percentage_delta": after.percentage - before.percentage,
            "lines_delta": after.covered_lines - before.covered_lines,
            "total_delta": after.total_lines - before.total_lines
        }
