apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chimera-live-services
  namespace: shared
  labels:
    app: prometheus
    project: project-chimera
spec:
  selector:
    matchLabels:
      project: project-chimera
  namespaceSelector:
    matchNames:
      - live
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      targetLabel: service
