apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scenespeak-monitor
  namespace: shared
  labels:
    app: prometheus
    project: project-chimera
    component: scenespeak
spec:
  selector:
    matchLabels:
      app: scenespeak-agent
  namespaceSelector:
    matchNames:
      - live
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      targetLabel: service
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'scenespeak_.*'
      action: keep
